### ISSUE TITLE
Script lijkt niet meer te werken

### ISSUE THREAD

**Issue by Wasmachineman-NL** [ArnoldDeRuiter/MarktplaatsUserscript#20]
Lijkt erop dat die flikkers van Marktplaats ook achter dit script gekomen zijn en het geblokkeerd hebben :|

**Comment by mid-kid** [comment]
Lijkt me sterk dat ze het direct zouden blokkeren, maar de pagina is in ieder geval veranderd en de script moet geüpdatet worden

**Comment by ArnoldDeRuiter** [comment]
Er waren inderdaad onder andere wat element class namen veranderd, specifiek `mp-Listings-<something>` naar `hz-Listings-<something>`.

Ik heb het script nu iets flexibeler gemaakt zodat "*Listings-<something>" wordt geselecteerd als element, dus wanneer enkel simpelweg de prefix van classes, nu  `hz`, weer veranderd, zou het script moeten blijven werken.

Ik sluit deze issue alvast, maar mocht er iets stuk zijn gegaan of toch nog niet werken, laat het vooral weer weten!
