### ISSUE TITLE
Recent classname changes? 

### ISSUE THREAD

**Issue by just-Addict** [ArnoldDeRuiter/MarktplaatsUserscript#3]
Not sure but it looks like there's been some classname/id changes. 
Some parts of the script don't seem to work. (e.g. hiding the prompt to login top-right on Home)

Otherwise, nice work, especially the seller location link.

**Comment by ArnoldDeRuiter** [comment]
Thanks for the heads up!

I'll be testing and updating this Userscript some more soon, but for now I managed to prevent the login prompt you mentioned on the top-right from appearing at all.

I appreciate it. :)
