### ISSUE TITLE
Dank!

### ISSUE THREAD

**Issue by mahershalal2** [ArnoldDeRuiter/MarktplaatsUserscript#4]
Dank voor dit geweldige script! Van alle extensions en scripts die ik heb uitgeprobeerd is dit de enige die werkt.

Tampermonkey gaf wel een aantal foutmeldingen:

Ten eerste was er een probleem met regel 71:  "Expected { after 'if' condition," Ondanks het feit dat ik geen enkel verstand van jscript heb, heb ik het als volgt aangepast:

        // Negeer wanneer er een veld in gebruik is
        if ($(event.target).is('input, textarea')) {
            return;
        }

Vooralsnog lijkt dit te werken.

Verder klaagde Tampermonkey over $ en waitForKeyElements: "waitForKeyElements is undefined", dus heb ik de volgende regel toegevoegd na "// ==/UserScript==":

/* globals jQuery, $, waitForKeyElements */

Dit alles ter info.

Nogmaals dank!

**Comment by ArnoldDeRuiter** [comment]
Excuses voor de vertraging en bedankt voor de input! Leuk om te horen dit.
Ik heb de suggesties meegenomen en toegepast. :)

**Comment by jb222** [comment]
Ook dank! Ik zocht eigenlijk naar een script om de originele (grotere) foto's te kunnen bekijken, nu moet ik daarvoor steeds naar de dev mode. Leuke toevoeging? Verder valt me op dat er wel "@grant function addGlobalStyle" in de header staat, maar in plaats daarvan gebruik je de functie addGlobalStyle. Waarom is dat?
